### ISSUE TITLE
JACDAC V0 TODO

### ISSUE THREAD

**Issue by jamesadevine** [lancaster-university/codal-core#82]
- [X] Control Packet refactor
    - [X] devices should broadcast their drivers every 500 ms 
    - [X] as before, control packets should be routed by the logic driver to correct drivers
- [ ] Dynamic packet sizes
    - [ ] device should receive a JDPkt header which will contain the size and the checksum
    - [ ] device should then prepare to receive the remained of the packet
- [ ] Dynamic baud rate
    - [ ] the pulse should dictate the baud rate for communication 10 us is 1mbaud. (i.e. 10 bits at whatever baud)
    - [ ] a device should reconfigure the baud rate upon receiving the pulse and prepare to receive the packet
    - [ ] control packets should be sent at the lowest baud rate on the bus
- [ ] Error detection and recovery
    - [ ] JACDAC should have a dedicated timer for detecting error conditions
    - [ ] As before, bus errors are not permissible in JACDAC
    - [ ] Packet timeouts should be tighter as specified on JACDAC.org
    - [ ] minimum byte gap should be observed.
    - [ ] difference between lo pulse and transmitting baud rate should not be tolerated.

**Comment by jamesadevine** [comment]
I am going to make a single PR for all the changes above.

**Comment by jamesadevine** [comment]
Combining this issue with the PR
